version: '3.8'

services:

  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reservationdb
    ports:
      - "3306:3306"
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always

  service-discovery:
    build: ./service-discovery
    container_name: service-discovery
    ports:
      - "8761:8761"
    restart: always

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - service-discovery
    restart: always

  reservation-service:
    build: ./reservation-service
    container_name: reservation-service
    ports:
      - "8082:8082"
    depends_on:
      - mysql
      - service-discovery
      - rabbitmq
    restart: always

  payment-service:
    build: ./payment-service
    container_name: payment-service
    ports:
      - "8083:8083"
    depends_on:
      - service-discovery
      - rabbitmq
    restart: always

  customer-service:
    build: ./customer-service
    container_name: customer-service
    ports:
      - "8081:8081"
    depends_on:
      - service-discovery
    restart: always

  hotel-service:
    build: ./hotel-service
    container_name: hotel-service
    ports:
      - "8084:8084"
    depends_on:
      - service-discovery
    restart: always

  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "8085:8085"
    depends_on:
      - service-discovery
      - rabbitmq
    restart: always