apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservation
  template:
    metadata:
      labels:
        app: reservation
    spec:
      containers:
        - name: reservation-container
          image: reservation-service:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
