server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: reservation-service
          uri: lb://RESERVATION-SERVICE
          predicates:
            - Path=/reservation/**

        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/customer/**

        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**

        - id: hotel-service
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/hotel/**

        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/notification/**

eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka/
      #defaultZone: http://localhost:8761/eureka/