
server:
  port: 8081

spring:
  application:
    name: customer-service

    datasource:
      url: jdbc:mysql://mysql:3306/customerdb
      #url: jdbc:mysql://localhost:3307/customerdb
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka/
      #defaultZone: http://localhost:8761/eureka/