server:
  port: 8082

spring:
  application:
    name: reservation-service

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

  datasource:
    url: jdbc:mysql://mysql:3306/reservationdb
    #url: jdbc:mysql://localhost:3307/reservationdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

cloud:
  openfeign:
    circuitbreaker:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka/
      #defaultZone: http://eureka:8761/eureka/
      #defaultZone: http://localhost:8761/eureka/

resilience4j:
  circuitbreaker:
    instances:
      paymentService:
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always